import { Inter } from 'next/font/google'
import './globals.css'
import {Providers} from "./providers";

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Obonye Galekhutle CV',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    
      <Providers>
      <body>{children}</body>
      </Providers>
      
    
  )
}
